---
- name: Update and upgrade apt packages
  apt:
    upgrade: dist
    update_cache: yes
    autoremove:   yes
    force_apt_get: yes
  become: true
  
- name: add useful tooling
  apt:
    name: "{{ useful_tools }}"
    force_apt_get: yes
  become: true
  
- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  become: true
  